"""update data user table

Revision ID: 93846863b03b
Revises: cd7f232b56a7
Create Date: 2023-03-02 18:16:24.863872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision = '93846863b03b'
down_revision = 'cd7f232b56a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user = table('user_app', column('org_id', Integer))
    op.execute(user.update().
               values({'org_id': op.inline_literal(1)}))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
