"""Add column to user table

Revision ID: cd7f232b56a7
Revises: eb26421c9f5a
Create Date: 2023-03-02 17:41:28.177739

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import Column, INTEGER, ForeignKey

# revision identifiers, used by Alembic.
revision = 'cd7f232b56a7'
down_revision = 'eb26421c9f5a'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user_app', Column('org_id', INTEGER,
                  ForeignKey('user_orgarnization.id')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
