"""Insert data into user_orgarnization table

Revision ID: eb26421c9f5a
Revises: a32c6f590516
Create Date: 2023-03-02 16:32:01.002158

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String

# revision identifiers, used by Alembic.
revision = 'eb26421c9f5a'
down_revision = 'a32c6f590516'
branch_labels = None
depends_on = None

accounts_table = table('user_orgarnization', column('name', String(255)))


def upgrade():
    op.bulk_insert(accounts_table, [
        {'name': 'TMA'},
        {'name': 'TMA-BD'},
        {'name': 'TMA-US'},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
